# Generated by Django 6.0.5 on 2026-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_blocked_users_profile_desktop_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
