# Generated by Django 6.0.5 on 2026-07-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_active_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_theme',
            field=models.CharField(choices=[('system', 'Use system setting'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_theme',
            field=models.CharField(choices=[('green', 'Classic green'), ('blue', 'Ocean blue'), ('purple', 'Soft purple'), ('sand', 'Warm sand')], default='green', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_wallpaper',
            field=models.CharField(choices=[('doodle', 'Chat doodles'), ('plain', 'Plain'), ('soft', 'Soft gradient'), ('dark', 'Dark pattern')], default='doodle', max_length=12),
        ),
    ]
