# Generated by Django 6.0.5 on 2026-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_app_theme_profile_chat_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_chat_wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='chat_wallpapers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_wallpaper',
            field=models.CharField(choices=[('doodle', 'Chat doodles'), ('plain', 'Plain'), ('soft', 'Soft gradient'), ('dark', 'Dark pattern'), ('custom', 'Custom image')], default='doodle', max_length=12),
        ),
    ]
