# Generated by Django 6.0.5 on 2026-07-27 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_receipts(apps, schema_editor):
    Message = apps.get_model("chat", "Message")
    MessageReceipt = apps.get_model("chat", "MessageReceipt")
    receipts = []
    for message in Message.objects.prefetch_related("conversation__participants"):
        for participant in message.conversation.participants.all():
            if participant.pk == message.sender_id:
                continue
            receipts.append(MessageReceipt(
                message_id=message.pk,
                user_id=participant.pk,
                delivered_at=message.delivered_at,
                read_at=message.read_at if message.is_read else None,
            ))
    MessageReceipt.objects.bulk_create(receipts, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_description_conversation_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_message_recipient_receipt')],
            },
        ),
        migrations.RunPython(create_existing_receipts, migrations.RunPython.noop),
    ]
